"""images type

Revision ID: 0251ef51e1c7
Revises: 77dda20057de
Create Date: 2022-04-11 19:55:52.160509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0251ef51e1c7'
down_revision = '77dda20057de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
