"""token bearer entry_time

Revision ID: 205e71491890
Revises: 35cfbc51085d
Create Date: 2022-08-05 19:45:10.784287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205e71491890'
down_revision = '35cfbc51085d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bearertokens', sa.Column('entry_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bearertokens', 'entry_time')
    # ### end Alembic commands ###
