"""user level

Revision ID: 2214c952cad1
Revises: 205e71491890
Create Date: 2022-08-06 18:47:11.716934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2214c952cad1'
down_revision = '205e71491890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_users_name', 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_users_name', 'users', type_='unique')
    # ### end Alembic commands ###
