"""init

Revision ID: 2804f8cdd452
Revises: 9f34a0c00333
Create Date: 2022-04-07 10:15:31.569615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2804f8cdd452'
down_revision = '9f34a0c00333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('grant_type', sa.String(length=18), nullable=False),
    sa.Column('response_type', sa.String(length=4), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('default_scopes', sa.Text(), nullable=False),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('default_redirect_uri', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_clients_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uc_clients_client_id')
    )
    op.create_table('authcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('challenge', sa.String(length=128), nullable=False),
    sa.Column('challenge_method', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['clients.id'], name='fk_authcodes_clients_id_client'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_authcodes_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uc_authcodes_code')
    )
    op.create_table('bearertokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['clients.id'], name='fk_bearertokens_clients_id_client'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_bearertokens_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token', 'refresh_token', name='uc_bearertokens_access_token_refresh_token')
    )
    op.drop_table('imagebackgrounds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagebackgrounds',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_imagebackgrounds_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('bearertokens')
    op.drop_table('authcodes')
    op.drop_table('clients')
    # ### end Alembic commands ###
