"""token bearer (host, platform)

Revision ID: 35cfbc51085d
Revises: 9c6ea0aee80a
Create Date: 2022-08-05 09:11:16.536989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cfbc51085d'
down_revision = '9c6ea0aee80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bearertokens', sa.Column('host', sa.String(length=100), nullable=True))
    op.add_column('bearertokens', sa.Column('platform', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bearertokens', 'platform')
    op.drop_column('bearertokens', 'host')
    # ### end Alembic commands ###
