"""color

Revision ID: 3650e330d0e2
Revises: 762da65a267a
Create Date: 2022-04-17 22:38:47.364317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3650e330d0e2'
down_revision = '762da65a267a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
