"""color

Revision ID: 368d85121f71
Revises: 3650e330d0e2
Create Date: 2022-04-17 22:40:42.286880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368d85121f71'
down_revision = '3650e330d0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfacecolors', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interfacecolors', 'title')
    # ### end Alembic commands ###
