"""images

Revision ID: 3c1140133372
Revises: 0251ef51e1c7
Create Date: 2022-04-15 10:28:04.641376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c1140133372'
down_revision = '0251ef51e1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=200), nullable=False))
    op.drop_column('images', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
