"""token

Revision ID: 3c1d6dc17692
Revises: 89aae8a6dd55
Create Date: 2022-08-02 22:34:26.920262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1d6dc17692'
down_revision = '89aae8a6dd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
