"""client title

Revision ID: 4612dc2c3391
Revises: bee3ed6b14e2
Create Date: 2022-07-28 20:43:49.067801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4612dc2c3391'
down_revision = 'bee3ed6b14e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'title')
    # ### end Alembic commands ###
