"""images

Revision ID: 77dda20057de
Revises: 2804f8cdd452
Create Date: 2022-04-11 10:08:36.651304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dda20057de'
down_revision = '2804f8cdd452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_images_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagebackgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['images.id'], name='fk_imagebackgrounds_images_id_image'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_imagebackgrounds_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagebackgrounds')
    op.drop_table('images')
    # ### end Alembic commands ###
