"""token

Revision ID: 89aae8a6dd55
Revises: 7827daf34a1d
Create Date: 2022-08-02 22:28:40.018943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aae8a6dd55'
down_revision = '7827daf34a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
