"""Added account table

Revision ID: 8d8adeead70c
Revises: 2214c952cad1
Create Date: 2022-09-20 20:44:16.109652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8adeead70c'
down_revision = '2214c952cad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
