"""spec

Revision ID: 91c063d2807d
Revises: 368d85121f71
Create Date: 2022-07-19 10:11:36.999141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91c063d2807d'
down_revision = '368d85121f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialColor', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('specialTopic', sa.Boolean(), nullable=True))
    op.drop_column('users', 'autoColorSwitching')
    op.drop_column('users', 'autoBackgroundSwitching')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('autoBackgroundSwitching', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('autoColorSwitching', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'specialTopic')
    op.drop_column('users', 'specialColor')
    # ### end Alembic commands ###
