"""token

Revision ID: 9c6ea0aee80a
Revises: 3c1d6dc17692
Create Date: 2022-08-02 22:36:36.145831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6ea0aee80a'
down_revision = '3c1d6dc17692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
